// vue/src/page/add.vue
<template>
<div class="container">
  <div class="back" @click="$router.back()"><img src="../assets/image/arrow_down.png"></div>
  <div class="typeswitch">
    <div>
      <p :class="type==1?'active':''" @click="changeType(1)">支出</p>
      <p :class="type==2?'active':''" @click="changeType(2)">收入</p>
    </div>
  </div>
  <div class="typelist">
    <div v-for="(item,index) in typeList" :key="index" class="item" :class="index==active?'active':''" @click="changeActive(index)">
      <div class="icon"><img :src="index==active?item.activeIcon:item.icon"></div>
      <p>{{item.name}}</p>
    </div>
  </div>
  <div class="keyboard">
    <div class="head">
      <div class="remark"><span>备注：</span><input v-model="remark" @input=changeRemark></div>
      <div>{{money}}</div>
    </div>
    <div class="box">
      <div class="num">
        <div @click="setMoney('7')">7</div>
        <div @click="setMoney('8')">8</div>
        <div @click="setMoney('9')">9</div>
        <div @click="setMoney('4')">4</div>
        <div @click="setMoney('5')">5</div>
        <div @click="setMoney('6')">6</div>
        <div @click="setMoney('1')">1</div>
        <div @click="setMoney('2')">2</div>
        <div @click="setMoney('3')">3</div>
        <div @click="setMoney('.')">.</div>
        <div @click="setMoney('0')">0</div>
        <div @click="cancelMoney"><img src="../assets/image/cancel_icon.png"></img></div>
      </div>
      <div class="other">
        <div class="picker" @click=changeDate>
          {{date==now?'今天':date}}
        </div>
        <div class="done" @click="done">完 成</div>
      </div>
    </div>
  </div> 
</div>
</template>
<script>
import typeList from '@/assets/type'
import {formatTime} from '@/assets/util'
export default{
	data(){
		return {
			id:null,
	    type:1,//1支出 2收入
	    now: formatTime(new Date()),
	    date: formatTime(new Date()),
	    typeList: [],
	    active:0,
	    money:0,
	    remark:null
		}
	},
	created(){
		this.typeList=typeList.filter(v=>v.type==this.type)
    this.init()
	},
	methods:{
    init(){
      let id=this.$route.query.id
      if(id===undefined){return false}
      this.$ajax({
        method:'get',
        url:'/account',
        params:{id:id}
      }).then(res=>{
        this.id=id
        this.type=res.type
        this.date=res.year+'-'+(res.month<9?'0'+res.month:res.month)+'-'+(res.day<9?'0'+res.day:res.day)
        this.active=typeList.findIndex(v=>v.id==res.icon)
        this.money=res.money
        this.remark=res.remark
      })
    },
		changeType(type){
			this.type=type
			this.active=0
			this.typeList=typeList.filter(v=>v.type==type)
		},
		changeActive(index){
			this.active=index
		},
		changeDate(){
			this.$datepicker({
			  value:this.date.split('-'),
			  type:'date'
			}).then((value)=>{
				this.date=value.join('-')
			})
		},
    changeRemark(){
      if(this.remark.length>8){
        this.$toast({
          icon:require('@/assets/image/error_icon.png'),
          msg:'备注不超过8个字符'
        })
        this.remark = this.remark.slice(0,8)
      }
    },
		setMoney(num){
	    let money = this.money;
	    if (('' + money).indexOf('.') > -1 && (('' + money).split(".")[1].length>1||num == '.')) {
	      return false
	    }
	    if (num == '.'||(num=='0'&&money!=0)||money==='0.'){
	      this.money = money + num
	    }else{
	      this.money = +(money + num)
	    }
	  },
	  cancelMoney(){
	    let str = this.money + ''
	    this.money=str.slice(0, str.length-1)
	  },
		done(){
			let year = this.date.split('-')[0],
	      month = +this.date.split('-')[1],
	      day = +this.date.split('-')[2],
	      money = +this.money;
	    if (money===0){
        this.$toast({
          icon:require('@/assets/image/error_icon.png'),
          msg:'金额不能为0'
        })
	      return false
	    }
	    let icon = typeList.filter(v => v.type == this.type)[this.active].id,
	      data = { year, month,day,money, remark: this.remark, icon, type: this.type }
	    if (this.id===null){
	    	this.$ajax({
	    		method:'post',
	    		url:'/account/add',
	    		data:data
	    	}).then(res=>{
	    		this.$router.back()
	    	})
	    }else{
	    	this.$ajax({
	    		method:'post',
	    		url:'/account/update',
	    		data: {...data,id:this.id},
	    	}).then(res=>{
	    		this.$router.back()
	    	})
	    }
		}
	}
}
</script>
<style scoped>
.back{
  position: fixed;top: 0.293333rem;left: 0.293333rem;
  height: 0.8rem;width: 0.8rem;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.3);
  display: flex;
  justify-content: center;
  align-items: center
}
.back img{
  height: 0.64rem;width: 0.64rem;
  transform: rotate(90deg)
}
.container{
  margin-bottom: 6.0rem
}
.typeswitch{
  height: 1.333333rem;
  display: flex;
  align-items: center;
  justify-content: center
}
.typeswitch div{
  height: 0.8rem;
  width: 4.0rem;
  border:1px solid #03A9F4;
  display: flex;
  align-items: center;
  border-radius: 5px;
}
.typeswitch p{
  flex:1;
  font-size: 16px;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center
}
.typeswitch .active{
  background: #03A9F4;
  color:#fff;
}

.typelist{
  display: flex;
  flex-wrap: wrap;
  margin-top: 0.266667rem;
}
.typelist .item{
  width: 2.0rem;
  margin-bottom: 0.266667rem;
}
.typelist .active .icon{
  background: #03A9F4;
}
.typelist .icon{
  height: 1.066667rem;width: 1.066667rem;
  margin:0 auto;
  padding: 0.2rem;
  box-sizing: border-box;
  border:1px solid #666;
  border-radius: 50%
}
.typelist img{
  height: 100%;width:100%;
  display: block
}
.typelist p{
  display: block;
  text-align: center;
  font-size:12px;
  margin-top: 5px;
  color:#333;
}


.keyboard{
  position: fixed;bottom:0;left:0;
  width: 10rem;
  background: #fff;
  z-index: 100
}
.keyboard .head{
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 1.173333rem;
  padding: 0 0.4rem;
  border-top:1px solid #f1f1f1;
  font-size: 14px;
}
.keyboard .remark{
  display: flex;
  align-items: center;
  flex: 1;
}
.keyboard .remark input{
	height: 1rem;
	border: 0;
  outline: none;
  appearance: none;
}
.keyboard .box{
  display: flex;
  font-size: 16px;
}
.keyboard .num{
  width: 7.6rem;
  display: flex;
  flex-wrap: wrap
}
.keyboard .num div{
  width: 2.533333rem;
  height: 1.173333rem;
  display: flex;
  align-items: center;
  justify-content: center;
  border-left:1px solid #f1f1f1;
  border-top:1px solid #f1f1f1;
  box-sizing: border-box
}
.keyboard .box img{
  width: 1.173333rem;height: 1.173333rem;
}
.keyboard .other{
  flex:1;
  display: flex;
  flex-direction: column;
  border-left:1px solid #f1f1f1;
  border-top:1px solid #f1f1f1;
}
.keyboard .picker{
  height: 1.173333rem;
  font-size:14px;
  display: flex;
  align-items: center;
  justify-content: center
}
.keyboard .done{
  flex:1;
  background: #03A9F4;
  border-top:1px solid #03A9F4;
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center
}
</style>

// react/src/pages/add/index.jsx
import React, { Component } from 'react';
import ajax from '../../assets/ajax'
import typeList from '../../assets/type.js'
import styles from './index.css'
import {formatTime} from '../../assets/util'
import {datepicker} from '../../react-picker'
import toast from '../../component/toast'
class add extends Component {
  constructor() {
    super();
    this.state = {
      id:null,
      type:1,//1支出 2收入
      now: formatTime(new Date()),
      date: formatTime(new Date()),
      typeList: [],
      active:0,
      money:0,
      remark:''
    }
    this.init = this.init.bind(this);
    this.back = this.back.bind(this);
    this.changeRemark = this.changeRemark.bind(this);
    this.cancelMoney = this.cancelMoney.bind(this);
    this.changeDate = this.changeDate.bind(this);
    this.done = this.done.bind(this);
  };
  componentDidMount(){
    this.setState({
      typeList:typeList.filter(v=>v.type===this.state.type)
    })
    this.init()
  };
  init(){
    let id=this.props.match.params.id
    if(id===undefined){return false}
    ajax({
      method:'get',
      url:'/account',
      params:{id:id}
    }).then(row=>{
      if(row.code===203){
        this.props.history.push('/')
        return false
      }
      let res=row.data
      this.setState({
        id:id,
        type:res.type,
        date:res.year+'-'+(res.month<9?'0'+res.month:res.month)+'-'+(res.day<9?'0'+res.day:res.day),
        active:typeList.findIndex(v=>v.id===res.icon),
        money:res.money,
        remark:res.remark||''
      })
    })
  };
  back(){
    this.props.history.go(-1)
  };
  changeType(type){
    this.setState({
      type:type,
      active:0,
      typeList:typeList.filter(v=>v.type===type)
    })
  };
  changeActive(index){
    this.setState({
      active:index
    })
  };
  changeRemark(event){
    let remark=event.target.value
    if(remark.length>8){
      toast({
        icon:require('../../assets/image/error_icon.png'),
        msg:'备注不超过8个字符',
        time:1000
      })
      remark = remark.slice(0,8)
    }
    this.setState({
      remark:remark
    })
  };
  setMoney(num){
    let money = this.state.money;
    if (('' + money).indexOf('.') > -1 && (('' + money).split(".")[1].length>1||num === '.')) {
      return false
    }
    if (num === '.'||(num==='0'&&money!==0)||money==='0.'){
      money = money + num
    }else{
      money = +(money + num)
    }
    this.setState({
      money:money
    })
  };
  cancelMoney(){
    let str = this.state.money + ''
    this.setState({
      money:str.slice(0, str.length-1)
    })
  };
  changeDate(){
    datepicker({
      value:this.state.date.split('-'),
      type:'date'
    }).then(res=>{
      this.setState({
        date:res.join('-')
      })
    })
  };
  done(){
    let year = this.state.date.split('-')[0],
      month = +this.state.date.split('-')[1],
      day = +this.state.date.split('-')[2],
      money = +this.state.money;
    if (money===0){
      toast({
        icon:require('../../assets/image/error_icon.png'),
        msg:'金额不能为0'
      })
      return false
    }
    let icon = typeList.filter(v => v.type === this.state.type)[this.state.active].id,
      data = { year, month,day,money, remark: this.state.remark, icon, type: this.state.type }
    if (this.state.id===null){
      ajax({
        method:'post',
        url:'/account/add',
        data:data
      }).then(res=>{
        this.back()
      })
    }else{
      ajax({
        method:'post',
        url:'/account/update',
        data: {...data,id:this.state.id},
      }).then(res=>{
        this.back()
      })
    }
  };
  render() {
    return (
      <div className={styles.container}>
        <div className={styles.back} onClick={this.back}><img src={require("../../assets/image/arrow_down.png")} alt=""/></div>
        <div className={styles.typeswitch}>
          <div>
            <p className={this.state.type===1?styles.active:''} onClick={e=>this.changeType(1)}>支出</p>
            <p className={this.state.type===2?styles.active:''} onClick={e=>this.changeType(2)}>收入</p>
          </div>
        </div>
        <div className={styles.typelist}>
          {
            this.state.typeList.map((item,index)=>
              (
                <div key={index} className={styles.item+' '+ (index===this.state.active?styles.active:'')} onClick={e=>this.changeActive(index)}>
                  <div className={styles.icon}><img src={index===this.state.active?item.activeIcon:item.icon} alt=""/></div>
                  <p>{item.name}</p>
                </div>
              )
            )
          }
        </div>
        <div className={styles.keyboard}>
          <div className={styles.head}>
            <div className={styles.remark}><span>备注：</span><input value={this.state.remark} onInput={this.changeRemark}/></div>
            <div>{this.state.money}</div>
          </div>
          <div className={styles.box}>
            <div className={styles.num}>
              <div onClick={e=>this.setMoney('7')}>7</div>
              <div onClick={e=>this.setMoney('8')}>8</div>
              <div onClick={e=>this.setMoney('9')}>9</div>
              <div onClick={e=>this.setMoney('4')}>4</div>
              <div onClick={e=>this.setMoney('5')}>5</div>
              <div onClick={e=>this.setMoney('6')}>6</div>
              <div onClick={e=>this.setMoney('1')}>1</div>
              <div onClick={e=>this.setMoney('2')}>2</div>
              <div onClick={e=>this.setMoney('3')}>3</div>
              <div onClick={e=>this.setMoney('.')}>.</div>
              <div onClick={e=>this.setMoney('0')}>0</div>
              <div onClick={this.cancelMoney}><img src={require("../../assets/image/cancel_icon.png")} alt=""></img></div>
            </div>
            <div className={styles.other}>
              <div className={styles.picker} onClick={this.changeDate}>
                {this.state.date===this.state.now?'今天':this.state.date}
              </div>
              <div className={styles.done}  onClick={this.done}>完 成</div>
            </div>
          </div>
        </div> 
      </div>
    );
  }
}

export default add;
