// vue/src/vue-picker/picker/picker.vue
<template>
  <div class="am-picker" v-if="show">
  	<div class="am-shade" @click.prevent=close></div>
  	<div class="am-box" :class="activeClass">
  		<div class="am-head">
  			<input type="button" :value=closetext @click.prevent=close>
  			<h2>{{title}}</h2>
  			<input type="button" :value=oktext @click.prevent=success>
  		</div>
  		<div class="am-ul">
  			<div class="am-item" v-for="(item,m) in option" @touchmove.prevent=touchmove @touchstart.prevent=touchstart @touchend.prevent=touchend :index=m>
				<ul :style="'transform: translate3d(0px, '+topStyle[m]+'px, 0px)'" :index=m :class=endClass[m]>
					<li v-for="key in item" :class="key==value[m]?'active':''">{{key}}</li>
				</ul>
			</div>
			<div class="am-high"></div>
		</div>
  	</div>
  </div>
</template>
<script>
export default {
	data(){
		return{
			show:true,
			title:'请选择',
			value:[],
			option:[],
			activeClass:null,
			closetext:'关 闭',
			oktext:'确 定',
			topStyle:[],
			start:{
				top:'',
				style:'',
				move:'',
				value:''
			},
			flag:true,
			endClass:[],
			height:35
		}
	},
	created(){
		document.body.style.overflowY = 'hidden'
		this.initTop()
	},
	mounted(){
		setTimeout(()=>{
			this.activeClass='active'
		},0)
	},
	methods:{
		initTop(){
			let m;
			this.value.forEach( (value, index) =>{
				if(!this.option[index]){return false}
				m=this.option[index].findIndex(v=>v==value)
				if(m==-1){console.log('默认值设置错误');return false}
				this.topStyle[index]=-m*this.height
			});
		},
		success(){
			this.end(true)
		},
		close(){
			this.end(false)
		},
		end(status){
			document.body.style.overflowY = 'auto'
			this.show=false;
			if(this.value.length==1){
				this.callback(status,this.value[0])
			}else{
				this.callback(status,this.value)
			}
			this.$destroy(true);
      this.$el.parentNode.removeChild(this.$el);
		},
		touchstart(event){
			let index=event.target.parentNode.getAttribute("index")||event.target.getAttribute("index")
			this.endClass[index]=''
			this.start.top=event.targetTouches[0].pageY
			this.start.style=-this.topStyle[index]
			this.start.value=this.value[index]
		},
		touchmove(event){
			if(!this.flag){return false}
			this.flag=false;
			setTimeout(()=>{
				let index=event.target.parentNode.getAttribute("index")||event.target.getAttribute("index")
				this.start.move=event.targetTouches[0].pageY
				this.topStyle.splice(index, 1, -(this.start.style+this.start.top-this.start.move))
				this.flag=true
			},15)
		},
		touchend(event){
			let index=event.target.parentNode.getAttribute("index")||event.target.getAttribute("index")
			this.endClass[index]='end'
			setTimeout(()=>{
				let h=-this.topStyle[index],len=this.option[index].length-1
				if(h<=0){
					this.topStyle.splice(index, 1, 0)
					this.value.splice(index,1,this.option[index][0])
				}else if(h>this.height*len){
					this.topStyle.splice(index, 1, -this.height*len)
					this.value.splice(index,1,this.option[index][len])
				}else{
					let m;
					if(h%this.height>=this.height/2){
						m=Math.ceil(h/this.height)
					}else{
						m=Math.floor(h/this.height)
					}
					this.topStyle.splice(index, 1, -this.height*m)
					this.value.splice(index,1,this.option[index][m])
				}
				if(this.start.value!=this.value[index]&&typeof this.change =='function'){
					if(this.value.length==1){
						this.change(this.value[0],Number(index),this)
					}else{
						this.change(this.value,Number(index),this)
					}
				}
			},20)
		},
		scrollTop(index,value){
			let m=this.option[index].indexOf(value)
			this.topStyle.splice(index, 1, -this.height*m)
			this.value.splice(index,1,value)
		}
	}
}

</script>

<style>
.am-picker{
	position: fixed;top:0;left:0;
	z-index:100000;
	height:100%;width:100%;
	line-height: 35px;
	font-size: 16px;
	color:#999;
}
.am-picker .am-shade{
	position: fixed;height:100%;width:100%;
	background: rgba(0,0,0,0.3);
	-webkit-backdrop-filter:saturate(180%) blur(4px) brightness(2)
}

.am-picker .am-box{
	width:100%;
	background: #fff;
	position: absolute;bottom:-280px;left:0;
	transition: bottom 0.2s;
	text-align: center;
	height:280px;
	display: flex;
	flex-direction: column;

}
.am-picker .am-box.active{
	bottom:0;
} 

.am-picker .am-head{
	display: flex;
	height:40px;line-height: 40px;
	background: #fff;
	border-bottom:1px solid #eee;
}
.am-picker .am-head input{
	appearance: none;
	border:none;
	outline: none;
	background: none;
	font-size:14px;
	padding:0 20px;
	color:#26a2ff;
	width:72px;
}
.am-picker .am-head h2{
	font-size:16px;
	flex:1;
	margin:0;
	font-weight: normal;
	color:#333;
}
.am-picker .am-ul{
	display: flex;
	flex:1;
	-webkit-mask-box-image:linear-gradient(to top, transparent, transparent 5%, white 20%, white 80%, transparent 95%, transparent);
	position: relative;
}
.am-picker  .am-item{
	flex:1;
	overflow: hidden;
}
.am-picker .am-ul ul{
	padding: 0;
	margin:0;
	list-style: none;
	margin-top:90px;
}
.am-picker .am-ul ul.end{
	transition :transform 0.2s;
}
.am-picker .am-ul li{
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
.am-picker .am-ul li.active{
	color:#333;
}
.am-picker .am-high{
	position: absolute;top:90px;left:0;
	width:100%;height:35px;
	box-sizing: border-box;
	border: 1px solid #eee;
	border-left:0;
	border-right: 0;
	z-index: -1
}
</style>

// react/src/react-picker/picker/index.jsx
import React, { Component } from 'react';
import styles from './index.css'
class picker extends Component {
	constructor() {
    super();
    this.state = {
    	show:true,
			title:'请选择',
			value:[],
			option:[],
			activeClass:null,
			closetext:'关 闭',
			oktext:'确 定',
			topStyle:[],
			start:{
				top:'',
				style:'',
				move:'',
				value:''
			},
			endClass:[],
			height:35
    }
    this.initTop=this.initTop.bind(this)
    this.success=this.success.bind(this)
    this.close=this.close.bind(this)
    this.end=this.end.bind(this)
    this.scrollTop=this.scrollTop.bind(this)
  };
  componentDidMount(){
  	document.body.style.overflowY = 'hidden'
		this.initTop()
		setTimeout(()=>{
			this.setState({
				activeClass:'active'
			})
		},0)
		this.setState({
			option:this.props.option,
			value:this.props.value
		})
  };
  initTop(){
		let m,arr;
		this.props.value.forEach( (value, index) =>{
			if(!this.props.option[index]){return false}
			m=this.props.option[index].findIndex(v=>v==value)
			if(m===-1){console.log('默认值设置错误');return false}
			arr=this.state.topStyle
			arr[index]=-m*this.state.height
			this.setState({
				topStyle:arr
			})
		});
	};
	success(event){
		this.end(true)
		event.preventDefault()
	};
	close(event){
		this.end(false)
		event.preventDefault()
	};
	end(status){
		document.body.style.overflowY = 'auto'
		this.setState({
			show:false
		})
		if(this.props.value.length===1){
			this.props.callback(status,this.props.value[0])
		}else{
			this.props.callback(status,this.props.value)
		}
	};
	touchstart(event,index){
		let arr=this.state.endClass
		arr[index]=''
		this.setState({
			endClass:arr,
			start:{
				top:event.targetTouches[0].pageY,
				style:-this.state.topStyle[index],
				value:this.state.value[index]
			}
		})
		event.preventDefault()
	};
	touchmove(event,index){
		let arr=this.state.topStyle,
			move=event.targetTouches[0].pageY
		arr[index]=-(this.state.start.style+this.state.start.top-move)
		this.setState({
			start:Object.assign(this.state.start,{move:move}),
			topStyle:arr
		})
		event.preventDefault()
	};
	touchend(event,index){
		let h=-this.state.topStyle[index],len=this.state.option[index].length-1
		let endClass=this.state.endClass,
			topStyle=this.state.topStyle,
			value=this.state.value;
		endClass[index]=styles.end
		if(h<=0){
			topStyle[index]=0
			value[index]=this.state.option[index][0]
		}else if(h>this.state.height*len){
			topStyle[index]=-this.state.height*len
			value[index]=this.state.option[index][len]
		}else{
			let m;
			if(h%this.state.height>=this.state.height/2){
				m=Math.ceil(h/this.state.height)
			}else{
				m=Math.floor(h/this.state.height)
			}
			topStyle[index]=-this.state.height*m
			value[index]=this.state.option[index][m]
		}
		this.setState({
			endClass:endClass,
			topStyle:topStyle,
			value:value
		})
		if(this.state.start.value!==this.state.value[index]&&typeof this.props.change ==='function'){
			if(this.state.value.length===1){
				this.props.change(this.state.value[0],Number(index),this)
			}else{
				this.props.change(this.state.value,Number(index),this)
			}
		}
		event.preventDefault()
	};
	scrollTop(index,value){
		let m=this.state.option[index].indexOf(value)
		let topStyle=this.state.topStyle,
			valueItem=this.state.value;
		topStyle[index]=-this.state.height*m
		valueItem[index]=value
		this.setState({
			topStyle:topStyle,
			value:valueItem
		})
	};
  render() {
    return (
    	<div>
    	{
    		this.state.show&&
	    	<div className={styles['am-picker']}>
			  	<div className={styles['am-shade']} onClick={this.close}></div>
			  	<div className={styles['am-box']+' '+styles[this.state.activeClass]}>
			  		<div className={styles['am-head']}>
			  			<input type="button" value={this.state.closetext} onClick={this.close}/>
			  			<h2>{this.props.title}</h2>
			  			<input type="button" value={this.state.oktext} onClick={this.success}/>
			  		</div>
			  		<div className={styles['am-ul']}>
			  			{
			  				this.state.option.map((item,m)=>
			  					<div className={styles['am-item']} onTouchMove={e=>this.touchmove(e,m)} onTouchStart={e=>this.touchstart(e,m)} onTouchEnd={e=>this.touchend(e,m)} key={m}>
			  						<ul style={{transform: 'translate3d(0px, '+this.state.topStyle[m]+'px, 0px)'}} className={this.state.endClass[m]}>
			  							{
			  								item.map((val,n)=>
			  									<li className={val===this.state.value[m]?styles.active:''} key={n}>{val}</li>
			  								)
			  							}
			  						</ul>
			  					</div>
			  				)
			  			}
							<div className={styles['am-high']}></div>
						</div>
			  	</div>
			  </div>
			}
			</div>
    )
  }
}
export default picker;
